popfont="Arial,10,,ITALIC"
definition1="The text for the first pop-up window."
definition2="The text for the second pop-up window."
def_password="A secret word used to verify the authenticity of a person's identity for the purpose of gaining access to additional secret information"
def_highlighted_text="Clicking the highlighted text will either cause a popup definition to appear (like this); or cause the help viewer to jump to another location in the help pages. [click again to make the popup disappear]"
